const DAYS={"Torso A":"data/torso-a.json","Pierna A":"data/pierna-a.json","Torso B":"data/torso-b.json","Pierna B":"data/pierna-b.json"};
const DUR={"Torso A":"60–75 min","Pierna A":"55–70 min","Torso B":"60–75 min","Pierna B":"55–70 min"};
const KEY="bodygym_pt_data_v2";
const LEGACY_KEY="bodygym_pt_data_v1";
const EXDB="https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/";
const MEDIA={
 dominadas_neutras:"Pullups",press_inclinado_maquina:"Leverage_Incline_Chest_Press",remo_polea_baja:"Seated_Cable_Rows",contractor:"Butterfly",elevacion_lateral:"Side_Lateral_Raise",triceps_pushdown:"Triceps_Pushdown_-_Rope_Attachment",curl_scott:"Preacher_Curl",crunch_maquina:"Cable_Crunch",
 prensa:"Leg_Press",rumano:"Romanian_Deadlift",curl_femoral:"Lying_Leg_Curls",extension_cuad:"Leg_Extensions",hip_thrust:"Barbell_Hip_Thrust",gemelos:"Calf_Press_On_The_Leg_Press_Machine",crunch_pierna_a:"Cable_Crunch",
 press_pecho_b:"Leverage_Chest_Press",dominadas_o_jalon:"Pullups",remo_unilateral:"Seated_Cable_Rows",deltoide_posterior:"Reverse_Flyes",elevacion_lateral_b:"Side_Lateral_Raise",triceps_b:"Triceps_Pushdown_-_Rope_Attachment",curl_polea:"Standing_Biceps_Cable_Curl",pallof:"Pallof_Press",
 hip_thrust_b:"Barbell_Hip_Thrust",prensa_b:"Leg_Press",curl_femoral_b:"Lying_Leg_Curls",extension_cuad_b:"Leg_Extensions",hiperextensiones:"Hyperextensions_(Back_Extensions)",gemelos_b:"Calf_Press_On_The_Leg_Press_Machine",crunch_b:"Cable_Crunch"
};
const ERRORS={
 dominadas_neutras:["Balancearte para completar la repetición.","Encoger los hombros hacia las orejas.","Acortar la bajada cuando aún controlas el movimiento."],
 press_inclinado_maquina:["Dejar que los hombros se vayan hacia delante.","Abrir los codos en cruz.","Bajar más de lo que tolera el hombro."],
 remo_polea_baja:["Echar el tronco hacia atrás para mover más peso.","Encoger hombros al tirar.","Tirar con las manos en vez de llevar los codos atrás."],
 contractor:["Llevar los hombros hacia delante al cerrar.","Rebotar en el estiramiento.","Usar demasiado peso y recortar recorrido."],
 elevacion_lateral:["Balancear el cuerpo.","Encoger el trapecio.","Subir por encima del rango cómodo."],elevacion_lateral_b:["Balancear el cuerpo.","Encoger el trapecio.","Subir por encima del rango cómodo."],
 triceps_pushdown:["Separar los codos del cuerpo.","Mover hombros y torso.","Soltar la subida sin control."],triceps_b:["Separar los codos del cuerpo.","Mover hombros y torso.","Soltar la subida sin control."],
 curl_scott:["Despegar el brazo del apoyo.","Dejar caer el peso en la bajada.","Buscar impulso al final."],curl_polea:["Mover los codos hacia delante.","Balancear el tronco.","Perder la bajada controlada."],
 crunch_maquina:["Tirar con brazos o cuello.","Convertirlo en un movimiento de cadera.","Rebotar entre repeticiones."],crunch_pierna_a:["Tirar con brazos o cuello.","Convertirlo en un movimiento de cadera.","Rebotar entre repeticiones."],crunch_b:["Tirar con brazos o cuello.","Convertirlo en un movimiento de cadera.","Rebotar entre repeticiones."],
 prensa:["Despegar la pelvis o lumbar del respaldo.","Dejar caer las rodillas hacia dentro.","Forzar profundidad si molesta la rodilla."],prensa_b:["Despegar la pelvis o lumbar del respaldo.","Dejar caer las rodillas hacia dentro.","Forzar profundidad si molesta la rodilla."],
 rumano:["Redondear la espalda.","Bajar la barra por buscar profundidad en vez de tensión.","Flexionar demasiado las rodillas."],
 curl_femoral:["Rebotar el peso.","Levantar la cadera del apoyo.","Soltar la fase de bajada."],curl_femoral_b:["Rebotar el peso.","Levantar la cadera del apoyo.","Soltar la fase de bajada."],
 extension_cuad:["Dar impulso desde la cadera.","Bloquear la rodilla de forma agresiva.","Usar un rango que provoque dolor."],extension_cuad_b:["Dar impulso desde la cadera.","Bloquear la rodilla de forma agresiva.","Usar un rango que provoque dolor."],
 hip_thrust:["Hiperextender la zona lumbar arriba.","Rebotar abajo.","Colocar los pies demasiado lejos o cerca."],hip_thrust_b:["Hiperextender la zona lumbar arriba.","Rebotar abajo.","Colocar los pies demasiado lejos o cerca."],
 gemelos:["Rebotar en el tendón.","Hacer recorrido corto.","Acelerar tanto que pierdes la pausa."],gemelos_b:["Rebotar en el tendón.","Hacer recorrido corto.","Acelerar tanto que pierdes la pausa."],
 press_pecho_b:["Perder la retracción escapular.","Rebotar abajo.","Forzar un rango que moleste al hombro."],dominadas_o_jalon:["Balancearte.","Tirar detrás de la nuca.","Encoger hombros."],remo_unilateral:["Girar el tronco.","Encoger el hombro.","Tirar solo con el bíceps."],deltoide_posterior:["Usar impulso.","Elevar demasiado los hombros.","Convertirlo en un remo pesado."],pallof:["Dejar que el torso rote.","Usar demasiado peso.","Perder la posición de pelvis y costillas."],hiperextensiones:["Hiperextender arriba.","Redondear la espalda.","Usar impulso en vez de mover desde la cadera."]
};
function $(id){return document.getElementById(id)}
function freshState(){return{logs:[],measures:[],pantry:{},mealDone:{},mealOverrides:{},machinePhotos:{},shoppingChecked:{}}}
function load(){let raw=null;try{raw=localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY)}catch(e){}let s=freshState();if(raw){try{s={...s,...JSON.parse(raw)}}catch(e){}}if(!s.pantry||!Object.keys(s.pantry).length){DEFAULT_PANTRY.forEach(id=>s.pantry[id]=true)}return s}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){alert("El almacenamiento del móvil está lleno. Prueba a borrar alguna foto de máquina.")}}
function today(){return new Date().toISOString().slice(0,10)}
function datef(d){return new Date(d+"T00:00:00").toLocaleDateString("es-ES")}
function tab(id){document.querySelectorAll(".tab,.tab-btn").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelector(`[data-tab="${id}"]`).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function exall(){return Object.entries(routine).flatMap(([day,a])=>a.map(x=>({...x,day})))}
function last(id){return state.logs.filter(x=>x.exerciseId===id).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]||null}
function range(s){const a=s.replace(/[–—]/g,"-").split("-");return +(a[1]||a[0])}
function suggest(ex){const l=last(ex.id);if(!l)return"Primera vez: usa un peso que deje 1–2 RIR.";const rs=l.series.map(s=>+s.reps||0),top=range(ex.reps);return rs.length>=ex.sets&&rs.every(v=>v>=top)?`✅ Cumplido con ${l.weight} kg: sube peso la próxima vez.`:`➡️ Mantén ${l.weight} kg e intenta +1 repetición total (última vez ${rs.join("/")}).`}
function machineKey(ex){const n=(ex.machineNumber||"").toLowerCase();if(n.includes("32/33"))return"machine-32-33";if(n.includes("nº 8")||n.includes("n° 8"))return"machine-8";if(n.includes("19"))return"machine-19";if(n.includes("14"))return"machine-14";if((ex.machine||"").toLowerCase().includes("smith"))return"machine-smith";return ex.id}
function demoUrl(id,n){return EXDB+encodeURIComponent(id)+"/"+n+".jpg"}
function mediaHtml(ex){const key=machineKey(ex),photo=state.machinePhotos[key],db=MEDIA[ex.id];return `<div class="media-block">
 <div class="machine-photo-card"><h4>1 · Máquina real de Bodygym</h4>${photo?`<img class="machine-photo" src="${photo}" alt="Máquina real de Bodygym"><div class="machine-actions"><button class="secondary" onclick="pickMachinePhoto('${ex.id}')">Cambiar foto</button><button class="danger-lite" onclick="removeMachinePhoto('${ex.id}')">Eliminar foto</button></div>`:`<div class="machine-empty"><div><span class="camera">📷</span><b>${ex.machineNumber||"Máquina sin número confirmado"}</b><p class="muted">Haz una foto de la máquina concreta. Se guardará en este móvil y se reutilizará en ejercicios de la misma estación.</p><button class="primary" onclick="pickMachinePhoto('${ex.id}')">Añadir foto real</button></div></div>`}<input hidden id="photo_${ex.id}" type="file" accept="image/*" capture="environment" onchange="saveMachinePhoto('${ex.id}',this)"></div>
 ${db?`<div class="exercise-demo"><h4>2 · Ejercicio real: inicio y fin</h4><div class="pose-grid"><div class="pose-card"><span class="pose-label">INICIO</span><img class="pose-img" src="${demoUrl(db,0)}" alt="${ex.name} posición inicial" onerror="this.parentElement.style.display='none'"></div><div class="pose-card"><span class="pose-label">FIN</span><img class="pose-img" src="${demoUrl(db,1)}" alt="${ex.name} posición final" onerror="this.parentElement.style.display='none'"></div></div><div class="source-note">Imágenes de movimiento: Free Exercise DB (dominio público).</div><a class="video-btn" href="${ex.videoUrl}" target="_blank" rel="noopener">3 · Ver vídeo real del ejercicio</a></div>`:`<a class="video-btn" href="${ex.videoUrl}" target="_blank" rel="noopener">Ver vídeo real del ejercicio</a>`}
 </div>`}
function renderDays(){const w=$("daysGrid");w.innerHTML="";for(const d of Object.keys(DAYS)){const x=document.createElement("div");x.className="day-card";x.innerHTML=`<h3>${d}</h3><p class="muted">${routine[d].length} ejercicios · ${DUR[d]}</p><p>Máquina, inicio/fin, vídeo, técnica y registro de series.</p>`;x.onclick=()=>{tab("rutina");$("daySelect").value=d;renderRoutine()};w.appendChild(x)}}
function renderSelects(){$("daySelect").innerHTML=Object.keys(DAYS).map(d=>`<option>${d}</option>`).join("");$("historyExercise").innerHTML='<option value="">Todos</option>'+exall().map(e=>`<option value="${e.id}">${e.name} — ${e.day}</option>`).join("")}
function seriesRows(ex){let s="";for(let i=1;i<=ex.sets;i++)s+=`<tr><td>Serie ${i}</td><td><input id="${ex.id}_r${i}" type="number" min="0" placeholder="reps"></td></tr>`;return s}
function renderRoutine(){const d=$("daySelect").value||Object.keys(DAYS)[0];$("daySummary").innerHTML=`<b>${d} · ${DUR[d]}</b><br><span class="muted">Grandes 1–2 RIR. Aislamientos 0–1 RIR. Las fotos reales de Bodygym se guardan en el móvil.</span>`;const w=$("routineContainer");w.innerHTML="";for(const ex of routine[d]){const l=last(ex.id),errs=ERRORS[ex.id]||["No sacrifiques técnica por mover más peso.","Evita rebotes o impulso.","Detén el ejercicio si aparece dolor articular claro."];const c=document.createElement("div");c.className="exercise-card";c.innerHTML=`<div class="exercise-head"><h3>${ex.name}</h3><span class="muted">${ex.machine}</span></div><div class="exercise-layout"><div>${mediaHtml(ex)}</div><div><div class="info-grid"><div class="info"><small>Series</small><br><b>${ex.sets}</b></div><div class="info"><small>Reps</small><br><b>${ex.reps}</b></div><div class="info"><small>RIR</small><br><b>${ex.rir}</b></div><div class="info"><small>Descanso</small><br><b>${ex.rest}</b></div></div><p><b>Máquina:</b> ${ex.machine}</p><div class="chips"><span>Bodygym: ${ex.machineNumber||"Sin número"}</span><span>${ex.machineConfidence||"por confirmar"}</span></div>${ex.machineDetail?`<p class="muted"><b>Detalle:</b> ${ex.machineDetail}</p>`:""}<p><b>Ajuste / guía:</b> ${ex.visual}</p><h4>Técnica</h4><ul>${ex.cues.map(x=>`<li>${x}</li>`).join("")}</ul><div class="errors-box"><h4>Errores a evitar</h4><ul>${errs.map(x=>`<li>${x}</li>`).join("")}</ul></div><p><b>Progresión:</b> ${ex.progression}</p>${ex.notes?`<p><b>Nota:</b> ${ex.notes}</p>`:""}<div class="summary"><b>Sugerencia:</b><br>${suggest(ex)}${l?`<p class="muted">Último: ${datef(l.date)} · ${l.weight} kg · ${l.series.map(s=>s.reps).join("/")} · dolor ${l.pain||0}/10</p>`:""}</div></div></div><hr><div class="grid3"><input id="${ex.id}_date" type="date" value="${today()}"><input id="${ex.id}_weight" type="number" step=".5" placeholder="Peso / lastre kg"><input id="${ex.id}_rir" type="number" min="0" max="4" placeholder="RIR final"></div><table class="sets"><thead><tr><th>Serie</th><th>Reps</th></tr></thead><tbody>${seriesRows(ex)}</tbody></table><div class="grid3"><input id="${ex.id}_pain" type="number" min="0" max="10" placeholder="Dolor 0–10"><textarea id="${ex.id}_notes" placeholder="Notas"></textarea><button class="primary" onclick="saveEx('${d}','${ex.id}')">Guardar ejercicio</button></div>`;w.appendChild(c)}}
window.pickMachinePhoto=function(id){const el=$("photo_"+id);if(el)el.click()};
function resizePhoto(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{const max=900,scale=Math.min(1,max/im.width),w=Math.round(im.width*scale),h=Math.round(im.height*scale),cv=document.createElement("canvas");cv.width=w;cv.height=h;cv.getContext("2d").drawImage(im,0,0,w,h);resolve(cv.toDataURL("image/jpeg",.68))};im.src=r.result};r.readAsDataURL(file)})}
window.saveMachinePhoto=async function(id,input){const file=input.files&&input.files[0];if(!file)return;const ex=exall().find(x=>x.id===id);try{state.machinePhotos[machineKey(ex)]=await resizePhoto(file);save();renderRoutine()}catch(e){alert("No he podido guardar la foto.")}};
window.removeMachinePhoto=function(id){const ex=exall().find(x=>x.id===id);delete state.machinePhotos[machineKey(ex)];save();renderRoutine()};
window.saveEx=function(day,id){const ex=exall().find(x=>x.id===id),ss=[];for(let i=1;i<=ex.sets;i++)ss.push({set:i,reps:+$(id+"_r"+i).value||0});if(ss.every(s=>!s.reps))return alert("Mete repeticiones antes de guardar.");state.logs.push({id:Date.now()+Math.random(),date:$(id+"_date").value||today(),time:new Date().toISOString(),day,exerciseId:id,exerciseName:ex.name,weight:+$(id+"_weight").value||0,rirLast:+$(id+"_rir").value||0,pain:+$(id+"_pain").value||0,notes:$(id+"_notes").value||"",series:ss});save();renderRoutine();renderHistory();alert("Registro guardado")};
function renderHistory(){const f=$("historyExercise").value;let a=[...state.logs].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));if(f)a=a.filter(x=>x.exerciseId===f);$("historySummary").innerHTML=a.length?`<b>${a.length}</b> registros · último ${datef(a[0].date)}`:"Aún no hay registros";$("historyList").innerHTML=a.map(x=>`<div class="history-item"><b>${x.exerciseName}</b> · <span class="muted">${x.day}</span><br>${datef(x.date)} · ${x.weight} kg · <b>${x.series.map(s=>s.reps).join(" / ")}</b> · RIR ${x.rirLast} · dolor ${x.pain||0}/10${x.notes?`<p class="muted">${x.notes}</p>`:""}</div>`).join("")}
function renderMeasures(){const a=[...state.measures].sort((a,b)=>b.date.localeCompare(a.date));if(!a.length){$("measureSummary").textContent="Guarda peso y cintura 1 vez por semana.";$("measureList").innerHTML="";return}const z=a[0],o=a[a.length-1];$("measureSummary").innerHTML=`Última: <b>${z.weight} kg · ${z.waist} cm</b><br><span class="muted">Cambio desde la primera: ${(z.weight-o.weight).toFixed(1)} kg · ${(z.waist-o.waist).toFixed(1)} cm</span>`;$("measureList").innerHTML=a.map(x=>`<div class="measure-item"><b>${datef(x.date)}</b> · ${x.weight} kg · ${x.waist} cm</div>`).join("")}
function measure(){const w=+$("measureWeight").value,q=+$("measureWaist").value;if(!w||!q)return alert("Mete peso y cintura");state.measures.push({date:$("measureDate").value||today(),weight:w,waist:q});save();renderMeasures();$("measureWeight").value=$("measureWaist").value=""}

function meal(id,title,items,protein,locked=false){return{id,title,items,protein,locked}}
function item(food,name,qty){return{food,name,qty}}
const BREAKFAST=()=>meal("breakfast","Desayuno",[item("avena","Avena","70 g"),item("leche","Leche semidesnatada","250 ml"),item("whey","Proteína whey","30 g"),item("canela","Canela","al gusto")],"≈35 g",true);
const SNACK_A=()=>meal("snack","Merienda",[item("yogur","Yogur griego 0 %","250 g"),item("cottage","Cottage","100 g"),item("arandanos","Arándanos","100 g")],"≈32 g");
const SNACK_B=()=>meal("snack","Merienda",[item("yogur","Yogur griego 0 %","250 g"),item("whey","Proteína whey","20 g"),item("pina","Piña","150 g")],"≈35 g");
const WEEK=[
 [BREAKFAST(),meal("lunch","Comida",[item("pollo","Pechuga de pollo","180 g"),item("patata","Patata cocida","300 g"),item("ensalada","Ensalada","grande"),item("aove","AOVE","10 g")],"≈45 g"),SNACK_A(),meal("dinner","Cena",[item("lomo","Lomo fresco","180 g"),item("patata","Patata cocida","220 g"),item("tomate","Tomate / ensalada","al gusto")],"≈42 g")],
 [BREAKFAST(),meal("lunch","Comida",[item("garbanzos","Garbanzos escurridos","250 g"),item("atun","Atún al natural","120 g"),item("tomate","Tomate y cebolla","al gusto"),item("aove","AOVE","10 g")],"≈48 g"),SNACK_B(),meal("dinner","Cena",[item("sardinas","Sardinas en lata","2 latas"),item("patata","Patata cocida","250 g"),item("ensalada","Ensalada","grande")],"≈38 g")],
 [BREAKFAST(),meal("lunch","Comida",[item("lomo","Lomo fresco","180 g"),item("pasta","Pasta seca","90 g"),item("ensalada","Ensalada","grande")],"≈45 g"),SNACK_A(),meal("dinner","Cena",[item("pollo","Pechuga de pollo","180 g"),item("patata","Patata cocida","250 g"),item("ensalada","Ensalada","grande")],"≈45 g")],
 [BREAKFAST(),meal("lunch","Comida",[item("pollo","Pechuga de pollo","170 g"),item("garbanzos","Garbanzos escurridos","180 g"),item("tomate","Tomate / cebolla","al gusto")],"≈50 g"),SNACK_B(),meal("dinner","Cena",[item("salmon","Salmón ahumado","150 g"),item("patata","Patata cocida","250 g"),item("ensalada","Ensalada","grande")],"≈35 g")],
 [BREAKFAST(),meal("lunch","Comida",[item("lomo","Lomo fresco","180 g"),item("patata","Patata cocida","300 g"),item("ensalada","Ensalada","grande")],"≈42 g"),SNACK_A(),meal("dinner","Cena",[item("sardinas","Sardinas en lata","2 latas"),item("patata","Patata cocida","250 g"),item("tomate","Tomate","al gusto")],"≈38 g")],
 [BREAKFAST(),meal("lunch","Comida",[item("atun","Atún al natural","160 g"),item("pasta","Pasta seca","90 g"),item("ensalada","Ensalada","grande"),item("aove","AOVE","10 g")],"≈45 g"),SNACK_B(),meal("dinner","Cena",[item("pollo","Pechuga de pollo","180 g"),item("patata","Patata cocida","250 g"),item("aguacate","Aguacate","70 g")],"≈45 g")],
 [BREAKFAST(),meal("lunch","Comida",[item("lomo","Lomo fresco","180 g"),item("garbanzos","Garbanzos escurridos","200 g"),item("ensalada","Ensalada","grande")],"≈48 g"),SNACK_A(),meal("dinner","Cena",[item("salmon","Salmón ahumado","150 g"),item("patata","Patata cocida","250 g"),item("tomate","Tomate / ensalada","al gusto")],"≈35 g")]
];
const DAY_NAMES=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
const SWAPS={
 lunch:[
  meal("lunch","Comida",[item("pollo","Pechuga de pollo","180 g"),item("patata","Patata cocida","300 g"),item("ensalada","Ensalada","grande")],"≈45 g"),
  meal("lunch","Comida",[item("lomo","Lomo fresco","180 g"),item("patata","Patata cocida","300 g"),item("ensalada","Ensalada","grande")],"≈42 g"),
  meal("lunch","Comida",[item("atun","Atún al natural","150 g"),item("pasta","Pasta seca","90 g"),item("tomate","Tomate / rúcula","al gusto")],"≈44 g"),
  meal("lunch","Comida",[item("garbanzos","Garbanzos escurridos","250 g"),item("atun","Atún al natural","120 g"),item("tomate","Tomate y cebolla","al gusto")],"≈48 g")
 ],
 snack:[SNACK_A(),SNACK_B(),meal("snack","Merienda",[item("cottage","Cottage","200 g"),item("arandanos","Arándanos","100 g"),item("kiwi","Kiwi","1 ud")],"≈25 g")],
 dinner:[
  meal("dinner","Cena",[item("pollo","Pechuga de pollo","180 g"),item("patata","Patata cocida","250 g"),item("ensalada","Ensalada","grande")],"≈45 g"),
  meal("dinner","Cena",[item("lomo","Lomo fresco","180 g"),item("patata","Patata cocida","220 g"),item("tomate","Tomate","al gusto")],"≈42 g"),
  meal("dinner","Cena",[item("sardinas","Sardinas en lata","2 latas"),item("patata","Patata cocida","250 g"),item("ensalada","Ensalada","grande")],"≈38 g"),
  meal("dinner","Cena",[item("salmon","Salmón ahumado","150 g"),item("patata","Patata cocida","250 g"),item("ensalada","Ensalada","grande")],"≈35 g")
 ]
};
const FOOD_GROUPS={"Proteínas":[["pollo","Pechuga de pollo"],["lomo","Lomo fresco"],["sardinas","Sardinas en lata"],["atun","Atún al natural"],["salmon","Salmón ahumado"],["garbanzos","Garbanzos"]],"Desayuno y lácteos":[["avena","Avena"],["leche","Leche semidesnatada"],["whey","Proteína whey"],["yogur","Yogur griego 0 %"],["cottage","Cottage"],["canela","Canela"]],"Hidratos":[["patata","Patata"],["pasta","Pasta"]],"Fruta y verdura":[["arandanos","Arándanos"],["pina","Piña"],["kiwi","Kiwi"],["ensalada","Lechuga / rúcula"],["tomate","Tomate / cebolla"],["aguacate","Aguacate"],["aove","AOVE"]]};
const DEFAULT_PANTRY=new Set(["avena","leche","whey","canela","yogur","cottage","arandanos","pollo","lomo","patata","atun","sardinas","garbanzos","ensalada","tomate","aove"]);
const SHOPPING={"Proteína":[["shop-pollo","Pechuga de pollo","≈ 1,0–1,2 kg"],["shop-lomo","Lomo fresco","≈ 700–800 g"],["shop-sardinas","Sardinas","4 latas"],["shop-atun","Atún al natural","5–6 latas"],["shop-salmon","Salmón ahumado","300 g"],["shop-whey","Whey","≈ 250 g"]],"Lácteos / desayuno":[["shop-avena","Avena","500 g"],["shop-leche","Leche semidesnatada","2 L"],["shop-yogur","Yogur griego 0 %","≈ 1,5–2 kg"],["shop-cottage","Cottage","≈ 700 g"]],"Hidratos":[["shop-patata","Patata","≈ 2,5–3 kg"],["shop-pasta","Pasta","500 g"],["shop-garbanzos","Garbanzos cocidos","3 botes"]],"Fruta / verdura":[["shop-arandanos","Arándanos","500–700 g"],["shop-pina","Piña","1 ud / bandeja"],["shop-kiwi","Kiwi","4–6 ud"],["shop-ensalada","Lechuga / rúcula","para 7 días"],["shop-tomate","Tomate / cebolla","para 7 días"],["shop-aguacate","Aguacates","2–3 ud"]]};
let routine={},state=load(),dietView="hoy";
function mondayIndex(jsDay){return(jsDay+6)%7}
function getMeal(dayIdx,id){const k=dayIdx+"|"+id,ov=state.mealOverrides[k];if(ov!==undefined&&SWAPS[id]&&SWAPS[id][ov])return SWAPS[id][ov];return WEEK[dayIdx].find(x=>x.id===id)}
function mealScore(m){return m.items.reduce((s,x)=>s+(state.pantry[x.food]?2:0),0)}
window.swapMeal=function(dayIdx,id){if(!SWAPS[id])return;const ranked=SWAPS[id].map((m,i)=>({i,s:mealScore(m)})).sort((a,b)=>b.s-a.s||a.i-b.i),k=dayIdx+"|"+id,current=state.mealOverrides[k],pos=ranked.findIndex(x=>x.i===current),next=ranked[(pos+1+ranked.length)%ranked.length];state.mealOverrides[k]=next.i;save();renderDiet()};
window.toggleMealDone=function(date,id){const k=date+"|"+id;state.mealDone[k]=!state.mealDone[k];save();renderDiet()};
function mealItemsHtml(m){return`<div class="meal-items">${m.items.map(x=>`<div class="meal-item"><span>${x.name}</span><b>${x.qty}</b></div>`).join("")}</div>`}
function mealCard(m,dayIdx,date){const done=!!state.mealDone[date+"|"+m.id];return`<div class="meal-card"><div class="diet-day-title"><h3>${m.title}</h3><span class="protein-badge">${m.protein} proteína</span></div>${mealItemsHtml(m)}<div class="meal-actions"><button class="meal-done ${done?"active":""}" onclick="toggleMealDone('${date}','${m.id}')">${done?"✓ Hecho":"Marcar hecho"}</button>${m.locked?`<button class="meal-locked" disabled>Desayuno fijo</button>`:`<button class="secondary" onclick="swapMeal(${dayIdx},'${m.id}')">Cambiar con lo que tengo</button>`}</div></div>`}
function renderDietToday(){const now=new Date(),idx=mondayIndex(now.getDay()),date=today(),meals=WEEK[idx].map(x=>getMeal(idx,x.id));return`<div class="panel"><div class="diet-day-title"><h2>${DAY_NAMES[idx]} · Hoy</h2><span class="protein-badge">4 comidas</span></div><p class="muted">Pulsa “Cambiar con lo que tengo” y priorizaré los alimentos que hayas marcado en Despensa.</p></div>${meals.map(m=>mealCard(m,idx,date)).join("")}`}
function renderDietWeek(){return WEEK.map((base,idx)=>`<details class="week-day" ${idx===mondayIndex(new Date().getDay())?"open":""}><summary>${DAY_NAMES[idx]}</summary>${base.map(x=>{const m=getMeal(idx,x.id);return`<div class="week-meal"><b>${m.title} · ${m.protein}</b>${mealItemsHtml(m)}</div>`}).join("")}</details>`).join("")}
window.togglePantry=function(id){state.pantry[id]=!state.pantry[id];save();renderDiet()};
function renderPantry(){let html=`<div class="pantry-card"><h2>Qué tengo en casa</h2><p>Marca lo que tienes. Al cambiar una comida, la app intentará usar primero estos alimentos.</p>`;for(const[g,foods]of Object.entries(FOOD_GROUPS)){html+=`<div class="pantry-category">${g}</div><div class="pantry-grid">${foods.map(([id,n])=>`<button class="pantry-toggle ${state.pantry[id]?"active":""}" onclick="togglePantry('${id}')">${state.pantry[id]?"✓ ":""}${n}</button>`).join("")}</div>`}html+=`<div class="ai-card"><h3>📷 Foto / IA</h3><p>La siguiente fase será poder fotografiar nevera, compra, ticket o etiqueta y añadir alimentos automáticamente. No pongo una clave de IA dentro de esta web porque sería inseguro; lo conectaremos con un backend cuando esta parte esté probada.</p></div></div>`;return html}
window.toggleShop=function(id){state.shoppingChecked[id]=!state.shoppingChecked[id];save();renderDiet()};
function renderShopping(){return`<div class="shopping-card"><h2>Lista semanal</h2><p class="muted">Cantidades orientativas para la base del menú. Marca lo que vayas comprando.</p>${Object.entries(SHOPPING).map(([g,rows])=>`<div class="shopping-group"><h3>${g}</h3>${rows.map(([id,n,q])=>`<label class="shop-row ${state.shoppingChecked[id]?"done":""}"><input type="checkbox" ${state.shoppingChecked[id]?"checked":""} onchange="toggleShop('${id}')"><span>${n} · <b>${q}</b></span></label>`).join("")}</div>`).join("")}</div>`}
function renderDiet(){document.querySelectorAll(".diet-nav").forEach(b=>b.classList.toggle("active",b.dataset.dietView===dietView));$("dietView").innerHTML=dietView==="hoy"?renderDietToday():dietView==="semana"?renderDietWeek():dietView==="despensa"?renderPantry():renderShopping()}
function exp(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="bodygym_pt_datos.json";a.click()}
function imp(f){const r=new FileReader;r.onload=e=>{try{state={...freshState(),...JSON.parse(e.target.result)};save();renderHistory();renderMeasures();renderRoutine();renderDiet();alert("Datos importados")}catch(_){alert("Archivo no válido")}};r.readAsText(f)}
async function init(){for(const[d,u]of Object.entries(DAYS))routine[d]=await fetch(u).then(r=>r.json());renderDays();renderSelects();$("measureDate").value=today();renderRoutine();renderHistory();renderMeasures();renderDiet();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}
document.querySelectorAll(".tab-btn").forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll(".diet-nav").forEach(b=>b.onclick=()=>{dietView=b.dataset.dietView;renderDiet()});$("daySelect").onchange=renderRoutine;$("historyExercise").onchange=renderHistory;$("saveMeasureBtn").onclick=measure;$("exportBtn").onclick=exp;$("importFile").onchange=e=>e.target.files[0]&&imp(e.target.files[0]);init();